<?xml version="1.0" encoding="utf-8"?>
<Database Name="QUIK" Class="QuikDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=QUIK;Persist Security Info=True;User ID=Misha2Kota" SettingsObjectName="Core.Properties.Settings" SettingsPropertyName="QUIKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="entity" Type="System.String" DbType="VarChar(50)" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="isUpdated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TradeDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Time" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SecCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Operation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Dealer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="QuikOrders">
    <Type Name="QuikOrder">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Time" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Operation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remaining" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>